CREATE TABLE mesa (
    numeroMesa INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    STATUS bit NOT NULL DEFAULT 1
);
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(200),
    PRECO DECIMAL(7,2) NOT NULL,
    STATUS bit default 1,
    categoria_id INT NOT NULL
);
CREATE TABLE CATEGORIA (
    id INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    NOME varchar(30) NOT NULL UNIQUE,
    STATUS bit NOT NULL DEFAULT 1
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA
    FOREIGN KEY (categoria_id)
    REFERENCES CATEGORIA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;

