<<<<<<< HEAD
CREATE TABLE MESA (
    ID INT PRIMARY KEY,
    STATUS boolean default true
);

CREATE TABLE PRODUTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(200),
    PRECO DECIMAL(7,2) NOT NULL,
    STATUS boolean NOT NULL DEFAULT true,
    IDCATEGORIA INT NOT NULL
);

CREATE TABLE CATEGORIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME varchar(30) NOT NULL UNIQUE,
    STATUS boolean NOT NULL DEFAULT true
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA
    FOREIGN KEY (IDCATEGORIA)
    REFERENCES CATEGORIA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
=======
CREATE TABLE mesa (
    numeroMesa INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    STATUS bit NOT NULL DEFAULT 1
);
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(200),
    PRECO DECIMAL(7,2) NOT NULL,
    STATUS bit default 1,
    categoria_id INT NOT NULL
);
CREATE TABLE CATEGORIA (
    id INT AUTO_INCREMENT PRIMARY KEY NOt NULL,
    NOME varchar(30) NOT NULL UNIQUE,
    STATUS bit NOT NULL DEFAULT 1
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA
    FOREIGN KEY (categoria_id)
    REFERENCES CATEGORIA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;

>>>>>>> 14b1f66c39d80ae001574df4844b7c69962e6cc4
