CREATE TABLE MESA (
    ID INT PRIMARY KEY,
    STATUS boolean default true
);

CREATE TABLE PRODUTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(200),
    PRECO DECIMAL(7,2) NOT NULL,
    STATUS boolean NOT NULL DEFAULT true,
    IDCATEGORIA INT NOT NULL
);

CREATE TABLE CATEGORIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME varchar(30) NOT NULL UNIQUE,
    STATUS boolean NOT NULL DEFAULT true
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA
    FOREIGN KEY (IDCATEGORIA)
    REFERENCES CATEGORIA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;