CREATE TABLE PEDIDO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TOTAL DECIMAL(7,2) NOT NULL DEFAULT 0.0,
    DATA DATETIME NOT NULL DEFAULT NOW(),
    STATUS ENUM('ABERTO','CANCELADO','ENCERRADO') NOT NULL DEFAULT 'ABERTO',
    numeroMesa INT NOT NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_MESA
    FOREIGN KEY (numeroMesa)
    REFERENCES MESA (numeroMesa)
    ON DELETE CASCADE ON UPDATE CASCADE;